### PR TITLE
PEP8 formatting and internationalization support

### PR DESCRIPTION
**Pull request by ribeiroit**
The aim of this pull request is the first step to contribute with project translation.

Although I didn't generate any translation yet, I let the code prepared to start it. My next step is to send you the portuguese brazilian locale messages.

I expect that you take a look and consider the changings that I'm sending. Please, let me know if you have some considerations.

Thanks for creating and sharing this project, it's being very useful to my company.

### CODE REVIEW

**Comment by aparsons** [comment]
@ribeiroit Thank you for your contributions! I'm glad to hear this project has been useful for your company. I'll be reviewing your pull request over the next couple days and offering feedback.

**Comment by aparsons** [comment]
Although I haven't looked thoroughly at the code submission yet, I would prefer to adhere to [Django's coding style](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/) which allows up to 119 characters for line lengths. 

> An exception to PEP 8 is our rules on line lengths. Don’t limit lines of code to 79 characters if it means the code looks significantly uglier or is harder to read. We allow up to 119 characters as this is the width of GitHub code review; anything longer requires horizontal scrolling which makes review more difficult. This check is included when you run flake8. Documentation, comments, and docstrings should be wrapped at 79 characters, even though PEP 8 suggests 72.

Lines longer than 119 characters should be refactored.

**Comment by ribeiroit** [comment]
If you prefer, please cancel this pull request and put everything on 119 columns.

**Comment by aparsons** [comment]
@ribeiroit I am closing this PR. If you would still like to add greater support for internationalization please submit those changes in a PR separate from any project-wide code formatting changes. Let me know if you have any questions!

**Pull request closed without merging**
